# Generated by Django 3.2.5 on 2021-07-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='admin_id',
            field=models.IntegerField(null=True),
        ),
    ]
