# Generated by Django 3.2.5 on 2021-07-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_classes_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='admin_id',
            field=models.IntegerField(),
        ),
    ]
