# Generated by Django 3.2.5 on 2021-07-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_alter_classes_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('despription', models.CharField(max_length=700)),
                ('deadline_date', models.CharField(max_length=50)),
                ('deadline_time', models.CharField(max_length=50)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('file', models.CharField(max_length=500)),
            ],
        ),
    ]
