# Generated by Django 3.2.5 on 2021-07-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_create_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('course', models.CharField(max_length=70)),
                ('department', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=30, unique=True)),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
