# Generated by Django 3.2.5 on 2021-07-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_id', models.IntegerField()),
                ('name', models.CharField(max_length=70)),
                ('reg_no', models.CharField(max_length=30, unique=True)),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=500)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
