# Generated by Django 3.2.5 on 2021-07-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='reg_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='submit',
            name='roll_no',
            field=models.CharField(max_length=50),
        ),
    ]
