# Generated by Django 3.2.5 on 2021-07-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0010_course_department_subject_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='class_id',
            new_name='subject_id',
        ),
    ]
