# Generated by Django 3.2.5 on 2021-07-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0011_rename_class_id_teacher_subject_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sunject_assign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('department_id', models.IntegerField()),
                ('subject', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
