# Generated by Django 3.2.5 on 2021-07-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0012_auto_20210727_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sunject_assign',
            new_name='Subject_assign',
        ),
    ]
