# Generated by Django 3.2.5 on 2021-07-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0013_rename_sunject_assign_subject_assign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('reg_no', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=70, null=True)),
            ],
        ),
    ]
