# Generated by Django 3.2.5 on 2021-07-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0015_alter_subject_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='department_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
