# Generated by Django 3.2.5 on 2021-07-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0016_auto_20210728_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_assign',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='subject_assign',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='subject_assign',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject_assign',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='subject_assign',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject_assign',
            name='department_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject_assign',
            name='subject_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject_assign',
            name='teachers_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject_assign',
            name='teachers_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject_assign',
            name='teachers_reg_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
