# Generated by Django 3.2.5 on 2021-07-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0017_auto_20210728_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='assignment_id',
            field=models.IntegerField(null=True),
        ),
    ]
