# Generated by Django 3.2.5 on 2021-07-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0018_alter_submit_assignment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='admin_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submit',
            name='assignment_id',
            field=models.IntegerField(),
        ),
    ]
