# Generated by Django 3.2.5 on 2021-08-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0019_auto_20210729_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading_materials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('despription', models.CharField(max_length=700)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('file', models.CharField(max_length=500)),
            ],
        ),
    ]
